(module info (lib "infotab.ss" "setup")
  (define name "No-Brainer")
  (define blurb `("A simple static checker that reports some local arity errors and unused bindings"))
  (define release-notes
    `("This version uses planet2."))
  (define categories `(devtools))
  (define tools '(("no-brainer-tool.rkt")))
  (define tool-names (list "Simple Static Checker"))
  (define compile-omit-paths '("private/test.rkt"))
  (define scribblings '(("no-brainer.scrbl" ())))
  (define version "20130227")
  )
